import { MetricDefinition } from '../types/definition';
import {
  AUTHORED_PRS_COUNT_V1,
  AUTHORED_PRS_WITH_BLOCKING_REVIEW_COUNT_V1,
  AUTHORED_PRS_WITH_TOUCHED_TESTS_V1,
  BLOCKED_PRS_RATE_V1,
  PR_LEAD_TIME_SECONDS_V1,
  PR_SIZE_FILES_CHANGED_MEDIAN_V1,
  PR_SIZE_LINES_CHANGED_MEDIAN_V1,
  PR_TIME_REVIEW_TO_MERGE_V1,
  PR_TIME_TO_FIRST_REVIEW_V1,
  PRS_TOUCHING_TESTS_RATE_V1,
} from './pullRequests';
import {
  REVIEW_FIRST_RESPONDER_COUNT_V1,
  REVIEW_LATENCY_SECONDS_AVG_V1,
  REVIEW_SUBSTANTIVE_COUNT_V1,
  REVIEWS_GIVEN_COUNT_V1,
  REVIEW_SUBSTANTIVE_RATE_V1,
  REVIEWS_COMMENT_AVG_V1,
} from './reviews';

export const ALL_METRICS: MetricDefinition[] = [
  // PR
  PR_LEAD_TIME_SECONDS_V1,
  AUTHORED_PRS_COUNT_V1,
  PR_SIZE_LINES_CHANGED_MEDIAN_V1,
  PR_TIME_TO_FIRST_REVIEW_V1,
  BLOCKED_PRS_RATE_V1,
  AUTHORED_PRS_WITH_BLOCKING_REVIEW_COUNT_V1,
  PR_SIZE_FILES_CHANGED_MEDIAN_V1,
  PR_TIME_REVIEW_TO_MERGE_V1,
  AUTHORED_PRS_WITH_TOUCHED_TESTS_V1,
  PRS_TOUCHING_TESTS_RATE_V1,

  // REVIEW
  REVIEWS_COMMENT_AVG_V1,
  REVIEWS_GIVEN_COUNT_V1,
  REVIEW_LATENCY_SECONDS_AVG_V1,
  REVIEW_FIRST_RESPONDER_COUNT_V1,
  REVIEW_SUBSTANTIVE_COUNT_V1,
  REVIEW_SUBSTANTIVE_RATE_V1,
];

export type MetricId = (typeof ALL_METRICS)[number]['id'];

export const METRIC_CATALOG_MAP: Record<string, MetricDefinition> =
  Object.fromEntries(ALL_METRICS.map((m) => [m.id, m]));
